apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80             # порт внутри кластера
      targetPort: 8080     # порт в контейнере
      nodePort: 30080      # порт на ноде (опционально, 30000-32767)
