FROM python:3.11-slim-bookworm

WORKDIR /app
COPY requirements.txt .
RUN echo "Build timestamp: $(date)"
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

CMD ["python", "--version"]
