FROM --platform=$BUILDPLATFORM golang:1.21-alpine AS builder
WORKDIR /app
COPY main.go .

# Компилируем статический бинарник
# CGO_ENABLED=0 - отключаем C-библиотеки (делаем бинарник статическим)
# GOOS и GOARCH - целевая платформа
#ARG TARGETOS
#ARG TARGETARCH
#RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH \
#    go build -o myapp main.go
RUN go build -o myapp main.go

FROM gcr.io/distroless/static
COPY --from=builder /app/myapp /myapp

ENTRYPOINT ["/myapp"]
