pipeline {
    agent {
        docker {
            image 'lachlanevenson/k8s-kubectl:v1.25.0'
            args '--entrypoint='
        }
    }
    stages {
        stage('Verify kubectl') {
            steps {
                sh 'kubectl version --client'
                sh 'echo "Agent работает в контейнере с kubectl!"'
            }
        }
    }
}
