FROM jenkins/jenkins:lts

# Переключимся на root для установки пакетов
USER root

# Установим Python3, pip и venv
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        python3-venv \
        python3-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Возвратимся к пользователю jenkins (безопасность)
USER jenkins
