pipeline {
    // Определяем, где запускать пайплайн
    agent any
    
    // Описание пайплайна
    stages {
        // Этап 1: Установка зависимостей
        stage('Install Dependencies') {
            steps {
		dir('AdvancedDevOps/m02/t02-pipeline-as-code-jenkinsfile') {
			echo 'Installing Python dependencies...'
                	sh 'python3 -m venv venv'
                	sh './venv/bin/pip install -r requirements.txt'
		}
            }
        }
        
        // Этап 2: Запуск тестов
        stage('Test') {
            steps {
		dir('AdvancedDevOps/m02/t02-pipeline-as-code-jenkinsfile') {
			echo 'Running tests with pytest...'
                	sh './venv/bin/python -m pytest -v'
		}
            }
        }
        
        // Этап 3: Финальное сообщение
        stage('Done') {
            steps {
                echo 'All tests passed successfully!'
            }
        }
    }
}
