pipeline {
    agent any
    
    stages {
        stage('Docker Check') {
            steps {
                echo 'Checking Docker availability...'
                sh 'docker --version'
                sh 'docker ps'
            }
        }

        stage('Build Image') {
            steps {
                dir('AdvancedDevOps/m02/t03-dind-in-jenkins-to-build-images') {
                    echo 'Building Docker image...'
                    sh 'docker build -t my-app-jenkins:${BUILD_NUMBER} .'
                }
            }
        }
    }
}
