FROM nginx:alpine
RUN apk add --no-cache curl
RUN echo "OK" > /usr/share/nginx/html/health.html
EXPOSE 80
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 CMD curl --fail http://localhost:80/health.html || exit 1
