services:
  web:
    # В dev мы собираем образ прямо из нашего локального кода
    build: .
    
    # Монтируем локальную папку в контейнер, чтобы изменения в коде 
    # применялись мгновенно без пересборки образа!
    volumes:
      - .:/app
      
    # Переопределяем переменную окружения
    environment:
      - ENV=development
