name: ci
on:
  pull_request:
    branches:
      - main
    path:
      - 'm08/t04-docker-build-and-push/**'
      - '!m08/t04-docker-build-and-push/*.md'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: m08/t04-docker-build-and-push
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: setup
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: run
        run: |
          pip install -r tests/requirements.txt
          PYTHONPATH=src pytest tests/

      - name: build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./docker/dockerfile
          push: true
          tags: ghcr.io/aesh-sudo/m08-t03-docker-build-and-push:latest
