name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: m08/t04-docker-build-and-push
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: setup
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: run
        run: |
          pip install -r tests/requirements.txt
          PYTHONPATH=src pytest tests/
